name: flutter_secure_token_manager
description: "Safely store access and refresh tokens, efficiently refreshing access tokens upon expiration."
version: 0.0.2
homepage: https://pub.dev/packages/flutter_secure_token_manager

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_lints: ^6.0.0